apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
data:
  MYSQL_USER: anand
  DB_PORT: '3306'
  MYSQL_DATABASE: claimmanagement
  DB_HOST: 'mysql-cluster-service'
  ALLOWED_CROSS_ORIGIN: '*'
  REACT_APP_API_BASE_URL: https://gtnrjlkhm.shop/api