apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-ui-deployment
spec:
  selector:
    matchLabels:
      app: bank-ui
  template:
    metadata:
      labels:
        app: bank-ui
    spec:
      containers:
      - name: myapp
        image: anandageethan/bank-ui:prod-env
        ports:
        - containerPort: 80
        env:
          - name: REACT_APP_API_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bank-config
                key: react_app_api_base_url