apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api-deployment
spec:
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
      - name: bank-api
        image: anandageethan/bank-api:latest
        ports:
        - containerPort: 9090
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: bank-app-config
                key: db_host
                
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: bank-app-config
                key: mysql_port

          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: bank-app-config
                key: mysql_database

          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: bank-app-config
                key: mysql_username

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bank-secret
                key: mysql_password