apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api-deployment
spec:
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
      - name: bank-api
        image: anandageethan/bank-api:latest
        ports:
        - containerPort: 9090
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_NAME
            value: claimmanagement
          - name: DB_USERNAME
            value: admin
          - name: DB_PASSWORD
            value: roto