apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    -- Declare variables
    SET @DB_NAME = 'claimmanagement';
    SET @DB_USER = 'anand';
    SET @DB_PASSWORD = 'password';

    -- Create the database if it does not exist
    CREATE DATABASE IF NOT EXISTS @DB_NAME;

    -- Switch to the created database
    USE @DB_NAME;

    -- Create the user if it does not exist and grant privileges
    CREATE USER IF NOT EXISTS @DB_USER@'%' IDENTIFIED BY @DB_PASSWORD;
    GRANT ALL PRIVILEGES ON @DB_NAME.* TO @DB_USER@'%';
    FLUSH PRIVILEGES;
