apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:                                   
        - name: mysql-storage
          persistentVolumeClaim: 
            claimName: mysql-pvc
      containers:
      - name: myapp
        image: anandageethan/bank-db:latest
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: '/var/lib/mysql'
            subPath: 'mysql'
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: claimmanagement
          - name: MYSQL_USER
            value: anand
          - name: MYSQL_PASSWORD
            value: 'password'