steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', 'cd', 'client']
- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', 'ls']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_CLIENT_IMAGE_NAME}:${_CLIENT_VERSION}', '-f', './client/Dockerfile', './client']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_SERVER_IMAGE_NAME}:${_SERVER_VERSION}','-f', './server/Dockerfile', './server']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_WORKER_IMAGE_NAME}:${_WORKER_VERSION}','-f', './worker/Dockerfile', './worker']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_CLIENT_IMAGE_NAME}:${_CLIENT_VERSION}']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVER_IMAGE_NAME}:${_SERVER_VERSION}']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_WORKER_IMAGE_NAME}:${_WORKER_VERSION}']

substitutions:
  _PROJECT_ID: k8s-project-425213
  _CLIENT_IMAGE_NAME: multi-client
  _SERVER_IMAGE_NAME: multi-server
  _WORKER_IMAGE_NAME: multi-worker
  _CLIENT_VERSION: c3.0
  _SERVER_VERSION: s3.0
  _WORKER_VERSION: w3.0
