options:
  logging: NONE
steps:
- name: ubuntu
  entrypoint: 'bash'
  args: ['-c', 'ls']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Setting up environment variables"
    export GOOGLE_APPLICATION_CREDENTIALS="${_GOOGLE_APPLICATION_CREDENTIALS}"

- name: 'hashicorp/terraform:light'
  id: Init
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Initializing Terraform"
    cd terraform
    terraform init

- name: 'hashicorp/terraform:light'
  id: Plan
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Planning Terraform"
    cd terraform
    terraform plan

- name: 'hashicorp/terraform:light'
  id: Apply
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Applying Terraform"
    cd terraform
    terraform apply -auto-approve

# Optional: Clean up the tfplan file
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     echo "Cleaning up"
#     rm tfplan

# Define substitutions for environment variables
substitutions:
  _GOOGLE_APPLICATION_CREDENTIALS: 'gs://terraform-state-bucket-bkup/credentials/k8s-project-425213-b9f5dc4dc5b6.json'
  _TF_STATE_BUCKET: 'gs://terraform-state-bucket-bkup/stateFiles'