steps:

- name: 'gcr.io/cloud-builders/git'
  args: ['rev-parse','HEAD']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t','gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:latest','-t','gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA', 'f', './k8s-own/react/myapp/Dockerfile', './k8s-own/react/myapp']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA']

substitutions:
  _PROJECT_ID: k8s-project-425213