steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_CLIENT_IMAGE_NAME}:${_VERSION}','client\Dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_SERVER_IMAGE_NAME}:${_VERSION}','server\Dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_WORKER_IMAGE_NAME}:${_VERSION}','worker\Dockerfile']

substitutions:
  _PROJECT_ID: k8s-project-425213
  _CLIENT_IMAGE_NAME: multi-client
  _SERVER_IMAGE_NAME: multi-server
  _WORKER_IMAGE_NAME: multi-worker