apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-ui
spec:
  selector:
    matchLabels:
      app: bank-ui
  template:
    metadata:
      labels:
        app: bank-ui
    spec:
      containers:
      - name: bank-ui
        image: anandageethan/bank-ui:working
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: bank-config
              key: REACT_APP_API_BASE_URL
