apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:  
  name: gtnrjlkhm-shop-tls
spec:  
  secretName: gtnrjlkhm-shop
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gtnrjlkhm.shop
  dnsNames:
    - gtnrjlkhm.shop
    - www.gtnrjlkhm.shop