apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: nginx-two
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: filestore-volume
          
      volumes:
      - name: filestore-volume
        persistentVolumeClaim:
          claimName: mypvc
