version: '3'
services:
  postgres:
    image: postgres
  redis:
    image: redis
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
  
  
