apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
data:
  mysql_username: anand
  mysql_port: '3306'
  mysql_database: claimmanagement
  db_host: 'mysql-cluster-service'
  allowed_cross_origin: '*'
  # react_app_api_base_url: http://localhost/api
  react_app_api_base_url: http://34.41.88.73/api
